"""rust-deps — package Rust crates (and their missing dependencies) for Fedora.

Every package lives in <root>/<crate>/ and is driven by rust2rpm:

    rust2rpm.toml             rust2rpm configuration (summary, tests, license
                              sources, cargo-toml-patch-comments, ...)
    cargo-toml-edits.toml     declarative Cargo.toml edits; rust-deps turns
                              them into <crate>-fix-metadata.diff
    rust-<crate>.spec         generated by rust2rpm — never edit by hand
    <crate>-fix-metadata*.diff, <crate>-<version>.crate, *.src.rpm

The package root is --root DIR, else $RUST_DEPS_ROOT, else the current
directory.  The full manual is references/MANUAL.md in the
fedora-rust-packaging skill; 'rust-deps doctor' checks the prerequisites.
'rust-deps tui' presents all of the commands in a text UI (python3-textual).

The tool is split into components by command domain (see the module
docstrings); the 'scripts/rust-deps' launcher next to this package runs it
straight from a checkout, no installation needed.

A Rust workspace is read from its own source tree: its member crates are not
asked of crates.io ('rust-deps workspace <dir>').
"""

from . import (
    archives,
    build,
    cli,
    config,
    copr,
    coprlogs,
    cratesio,
    distgit,
    doctor,
    edits,
    fedora,
    packages,
    pkginit,
    regen,
    resolver,
    review,
    reviewplan,
    reviewrequest,
    reviewstatus,
    srpm,
    status,
    targets,
    tmt,
    trial,
    tui_app,
    tui_form,
    tui_overview,
    tui_playbooks,
    tui_results,
    update,
    util,
    versions,
    workspace,
)
