"""rust-deps adopt and dist-git update handling."""

from __future__ import annotations

from pathlib import Path
import difflib
import json
import os
import re
import shutil
import subprocess
import textwrap
import time
import tomllib
import urllib.error
import urllib.parse
import urllib.request

from . import build
from . import config
from . import packages
from . import regen
from . import reviewplan
from . import reviewrequest
from . import util
from . import versions

DIST_GIT = "https://src.fedoraproject.org"
# dist-git files that are not packaging input: the spec is generated here, the rest is git and lookaside data
DIST_GIT_SKIP = {".gitignore", "sources", "changelog", "README.md", "gating.yaml"}


def dist_git_files(tree: list[dict], rpm_name: str) -> list[str]:
    """The dist-git files to take over: the regular files, except the spec and git/lookaside data."""
    return sorted(
        e["name"]
        for e in tree
        if e.get("type") == "file"
        and e["name"] not in DIST_GIT_SKIP
        and e["name"] != f"{rpm_name}.spec"
    )


def spec_similarity(ours: str, theirs: str) -> tuple[int, int]:
    """(lines that differ, lines compared) between two specs, ignoring the header comment and %changelog."""

    def norm(text: str) -> list[str]:
        text = text.split("\n%changelog", 1)[0]
        return [
            ln.rstrip()
            for ln in text.splitlines()
            if ln.strip() and not ln.startswith("# Generated by rust2rpm")
        ]

    a, b = norm(ours), norm(theirs)
    changed = sum(
        1
        for ln in difflib.unified_diff(a, b, lineterm="", n=0)
        if ln[:1] in "+-" and not ln.startswith(("+++", "---"))
    )
    return changed, max(len(a), len(b))


def adopt(
    pkg: packages.LocalPackage, branch: str, dry_run: bool, mark_only: bool = False
) -> bool:
    name = pkg.rpm_name
    try:
        commit = json.loads(
            reviewrequest._get(
                f"{DIST_GIT}/api/0/rpms/{name}/git/branches?with_commits=true"
            )
        )["branches"][branch]
        tree = json.loads(
            reviewrequest._get(f"{DIST_GIT}/api/0/rpms/{name}/tree/{commit}")
        )["content"]
        spec = reviewrequest._get(
            f"{DIST_GIT}/rpms/{name}/raw/{commit}/f/{name}.spec"
        ).decode()
    except (urllib.error.URLError, KeyError) as exc:
        util.action(f"{pkg.crate}: cannot read {name} {branch} from dist-git: {exc}")
        return False
    files = dist_git_files(tree, name)
    fedora_version = (re.search(r"^Version:\s+(\S+)", spec, re.M) or [None, None])[1]
    marker = (
        "# Adopted from Fedora's dist-git: the package is in Fedora.  rust-deps builds it in COPR only\n"
        "# where a target lacks this version, and files no review request for it.\n"
        f'package = "{name}"\nbranch = "{branch}"\ncommit = "{commit}"\nversion = "{fedora_version}"\n'
    )
    if mark_only or "rust2rpm.toml" not in files:
        # keep the local packaging (e.g. tuned for older targets), or there is none to take over (a spec
        # edited by hand, without rust2rpm.toml); the package is in Fedora either way
        why = "as asked" if mark_only else "dist-git has no rust2rpm.toml"
        util.info(
            f"== {pkg.crate}: {name} {branch} at {commit[:10]} (Fedora {fedora_version}): keeping the local "
            f"packaging ({why}), marked as in Fedora"
        )
        if not dry_run:
            (pkg.dir / config.DIST_GIT_FILE).write_text(
                marker.replace("# Adopted from", "# Marked from", 1)
                + f'packaging = "local"  # {why}\n'
            )
            if (pkg.dir / config.TARGETS_FILE).exists():
                (pkg.dir / config.TARGETS_FILE).unlink()
        return True
    ours, theirs = versions.parse_version(pkg.version or ""), versions.parse_version(
        fedora_version or ""
    )
    version = pkg.version if ours and theirs and ours > theirs else fedora_version
    util.info(
        f"== {pkg.crate}: {name} {branch} at {commit[:10]}: Fedora {fedora_version}, here {pkg.version}; "
        f"packaging {version}"
    )
    util.info(f"   files: {', '.join(files)}")
    if dry_run:
        return True
    backup = pkg.dir / ".rust-deps-backup" / f"adopt-{time.strftime('%Y%m%d-%H%M%S')}"
    backup.mkdir(parents=True)
    for f in [
        pkg.config_file,
        pkg.edits_file,
        pkg.dir / config.TARGETS_FILE,
        *pkg.dir.glob("*-fix-metadata.diff"),
        *(pkg.dir / n for n in files),
    ]:
        if f.exists() and not (backup / f.name).exists():
            shutil.move(str(f), backup / f.name)
    for n in files:
        (pkg.dir / n).write_bytes(
            reviewrequest._get(f"{DIST_GIT}/rpms/{name}/raw/{commit}/f/{n}")
        )
    pkg.edits_file.write_text(
        "# Adopted from Fedora's dist-git: Cargo.toml changes are in the hand-made\n"
        f"# {pkg.crate}-fix-metadata.diff, as there.  Edits here would replace it.\n"
    )
    (pkg.dir / config.DIST_GIT_FILE).write_text(marker)
    util.info(f"   earlier configuration kept in {backup}")
    if not regen.regen(
        packages.LocalPackage(pkg.crate, pkg.dir, pkg.version, pkg.name), version
    ):
        util.action(
            f"{pkg.crate}: regen with Fedora's packaging failed at {version}; if its fix-metadata.diff does "
            "not apply to this version, update it (rust2rpm -p) or express it in cargo-toml-edits.toml"
        )
        return False
    new = packages.local_packages(pkg.dir.parent)[pkg.crate]
    if version == fedora_version:
        changed, total = spec_similarity(new.spec.read_text(), spec)
        util.info(
            f"   the regenerated spec {'matches' if not changed else f'differs in {changed} of {total} lines from'} "
            f"Fedora's"
        )
    return True


DIST_GIT_ENV = "RUST_DEPS_DIST_GIT"  # where dist-git checkouts for updates live
UPDATE_STATE = "dist-git-update.json"  # {"checkout", "branch", "base", "version", "pushed", "pr_url"}
TMT_FILES = (".fmf/version", "plans/rust-deps.fmf")


def spec_sources(spec: Path) -> list[tuple[str, str]]:
    """(tag, value) of every Source and Patch, macros expanded (spectool -l)."""
    res = util.run(["spectool", "-l", str(spec)], capture_output=True)
    if res.returncode:
        util.die(f"spectool failed on {spec}:\n{res.stderr}")
    return [
        (tag, value.strip())
        for tag, _, value in (ln.partition(":") for ln in res.stdout.splitlines())
        if value
    ]


def update_files(pkg: packages.LocalPackage) -> tuple[dict[str, Path], list[Path]]:
    """The files of a dist-git update: (repository path -> local file, files for the lookaside cache)."""
    repo = {pkg.spec.name: pkg.spec, "rust2rpm.toml": pkg.config_file}
    lookaside = []
    for _, value in spec_sources(pkg.spec):
        if (
            "://" in value
        ):  # downloaded: the crate, license texts; "url#/name" names the file
            name = (
                value.rsplit("#/", 1)[1] if "#/" in value else value.rsplit("/", 1)[1]
            )
            lookaside.append(pkg.dir / name)
        else:
            repo[value] = pkg.dir / value
    for rel in TMT_FILES:
        if (pkg.dir / rel).exists():
            repo[rel] = pkg.dir / rel
    tests = pkg.dir / "tests" / "rust-deps"
    for f in sorted(tests.iterdir()) if tests.is_dir() else []:
        repo[f"tests/rust-deps/{f.name}"] = f
    return repo, lookaside


def toml_comments(text: str) -> list[str]:
    """cargo-toml-patch-comments and [tests] comments of a rust2rpm.toml."""
    try:
        cfg = tomllib.loads(text)
    except tomllib.TOMLDecodeError:
        return []
    return list(cfg.get("package", {}).get("cargo-toml-patch-comments", [])) + list(
        cfg.get("tests", {}).get("comments", [])
    )


def update_message(
    pkg: packages.LocalPackage, old_spec: str, old_config: str, added: list[str]
) -> str:
    """A commit message (and so, with %autochangelog, the changelog entry) for the update."""
    old_version = (re.search(r"^Version:\s+(\S+)", old_spec, re.M) or [None, None])[1]
    subject = (
        f"Update to {pkg.version}"
        if old_version != pkg.version
        else "Update the packaging"
    )
    old = set(toml_comments(old_config))
    lines = [c for c in toml_comments(pkg.config_file.read_text()) if c not in old]
    if any(a.startswith(("plans/", "tests/rust-deps/", ".fmf/")) for a in added):
        lines.append("add tmt tests for Fedora CI (generated by rust-deps)")
    return (
        subject
        + ("\n\n" + "\n".join(f"- {ln}" for ln in lines) if lines else "")
        + "\n"
    )


def git(checkout: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    res = util.run(["git", "-C", str(checkout), *args], capture_output=True)
    if check and res.returncode:
        util.die(f"git {' '.join(args)} failed in {checkout}:\n{res.stderr}")
    return res


def prepare_update(
    pkg: packages.LocalPackage, top: Path, branch: str | None, dry_run: bool
) -> bool:
    """A local commit in a dist-git checkout that updates the Fedora package to the local packaging,
    on the branch it was adopted from unless 'branch' names another."""
    dg = pkg.dist_git or {}
    if not dg:
        util.action(
            f"{pkg.crate}: not adopted from dist-git; run 'adopt {pkg.crate}' first"
        )
        return False
    adopted = dg.get("branch", "rawhide")
    branch = branch or adopted
    if dg.get("packaging") == "local":
        util.action(
            f"{pkg.crate}: marked with --mark-only, its packaging is for other targets; to propose "
            f"it to Fedora, 'adopt {pkg.crate}' without --mark-only"
        )
        return False
    name = pkg.rpm_name
    checkout = top / name
    if not (checkout / ".git").exists():
        util.info(f"   cloning {DIST_GIT}/rpms/{name}.git into {checkout}")
        if not dry_run:
            top.mkdir(parents=True, exist_ok=True)
            res = util.run(
                ["git", "clone", "-q", f"{DIST_GIT}/rpms/{name}.git", str(checkout)],
                capture_output=True,
            )
            if res.returncode:
                util.action(f"{pkg.crate}: cannot clone {name}: {res.stderr.strip()}")
                return False
    elif not dry_run:
        git(checkout, "fetch", "-q", "origin")
    if dry_run:
        util.info(
            f"   would prepare branch update-{pkg.version} of {checkout} from origin/{branch}"
        )
        return True
    head = git(checkout, "rev-parse", f"origin/{branch}").stdout.strip()
    if branch != adopted:
        # the recorded commit is on another branch: nothing to compare with
        util.warn(
            f"{pkg.crate}: adopted from dist-git {adopted}, updating {branch} as asked; "
            f"its packaging may differ from {adopted}'s"
        )
    elif dg.get("commit") and head != dg["commit"]:
        log = git(
            checkout, "log", "--oneline", f"{dg['commit']}..{head}", check=False
        ).stdout.strip()
        util.action(
            f"{pkg.crate}: dist-git {branch} moved since 'adopt' ({dg['commit'][:10]} -> {head[:10]}):\n"
            + textwrap.indent(log or "(history rewritten)", "      ")
            + f"\n   run 'adopt {pkg.crate}' again (it keeps the newer version here), redo the local "
            "changes, then 'dist-git' again"
        )
        return False
    local_branch = f"update-{pkg.version}"
    git(checkout, "checkout", "-q", "-B", local_branch, f"origin/{branch}")
    old_spec = git(checkout, "show", f"HEAD:{name}.spec", check=False).stdout
    old_config = git(checkout, "show", "HEAD:rust2rpm.toml", check=False).stdout
    repo, lookaside = update_files(pkg)
    missing = [str(f) for f in [*repo.values(), *lookaside] if not f.exists()]
    if missing:
        util.action(
            f"{pkg.crate}: missing {', '.join(missing)}; run 'srpm {pkg.crate}' first"
        )
        return False
    tracked = set(git(checkout, "ls-files").stdout.split())
    # patches that the local packaging no longer uses; other files (README, gating.yaml, ...) stay
    stale = sorted(
        f for f in tracked if f.endswith((".diff", ".patch")) and f not in repo
    )
    if stale:
        git(checkout, "rm", "-q", *stale)
    for rel, src in repo.items():
        (checkout / rel).parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, checkout / rel)
    for f in lookaside:
        shutil.copy2(f, checkout / f.name)
    if lookaside:
        if not shutil.which("fedpkg"):
            util.action(
                f"{pkg.crate}: fedpkg is needed to record the sources in dist-git: dnf install fedpkg"
            )
            return False
        res = util.run(
            ["fedpkg", "new-sources", "--offline", *(f.name for f in lookaside)],
            cwd=checkout,
            capture_output=True,
        )
        if res.returncode:
            util.action(
                f"{pkg.crate}: fedpkg new-sources --offline failed:\n{res.stdout}{res.stderr}"
            )
            return False
    git(
        checkout,
        "add",
        *repo,
        *(f for f in ("sources", ".gitignore") if (checkout / f).exists()),
    )
    added = [rel for rel in repo if rel not in tracked]
    if not git(checkout, "diff", "--cached", "--quiet", check=False).returncode:
        util.info(f"   {checkout}: no changes against dist-git {branch}")
        return True
    message = update_message(pkg, old_spec, old_config, added)
    res = util.run(
        ["git", "-C", str(checkout), "commit", "-q", "-s", "-F", "-"],
        input=message,
        capture_output=True,
    )
    if res.returncode:
        util.die(f"git commit failed in {checkout}:\n{res.stderr}")
    state = {
        "checkout": str(checkout),
        "branch": local_branch,
        "target": branch,
        "base": head,
        "version": pkg.version,
        "lookaside": [f.name for f in lookaside],
        "pushed": False,
    }
    (pkg.dir / UPDATE_STATE).write_text(json.dumps(state, indent=2) + "\n")
    util.info(f"   committed on {local_branch} in {checkout} (not pushed):")
    util.info(
        textwrap.indent(
            git(
                checkout, "show", "--stat", "--format=%s%n%n%b", "HEAD"
            ).stdout.rstrip(),
            "      ",
        )
    )
    return True


def push_update(pkg: packages.LocalPackage) -> bool:
    """Fork (once), upload the new sources to the lookaside cache, push the branch to the fork."""
    f = pkg.dir / UPDATE_STATE
    if not f.exists():
        util.action(f"{pkg.crate}: nothing prepared; run 'dist-git {pkg.crate}' first")
        return False
    if not shutil.which("fedpkg"):
        util.action(
            f"{pkg.crate}: fedpkg is needed to fork and upload the sources: dnf install fedpkg"
        )
        return False
    state = json.loads(f.read_text())
    checkout = Path(state["checkout"])
    remotes = [r for r in git(checkout, "remote").stdout.split() if r != "origin"]
    if not remotes:
        res = util.run(["fedpkg", "fork"], cwd=checkout, capture_output=True)
        if res.returncode:
            util.action(
                f"{pkg.crate}: fedpkg fork failed (it needs a dist-git API token: 'fedpkg "
                f"set-distgit-token'):\n{res.stdout}{res.stderr}"
            )
            return False
        remotes = [r for r in git(checkout, "remote").stdout.split() if r != "origin"]
    fork = remotes[0]
    res = util.run(
        ["fedpkg", "new-sources", *state["lookaside"]],
        cwd=checkout,
        capture_output=True,
    )
    if res.returncode:
        util.action(
            f"{pkg.crate}: uploading to the lookaside cache failed (packagers only; Kerberos ticket?):\n"
            f"{res.stdout}{res.stderr}"
        )
        return False
    if git(checkout, "status", "--porcelain", check=False).stdout.strip():
        git(checkout, "commit", "-q", "--amend", "--no-edit", "-a")
    git(checkout, "push", "-q", "-f", fork, state["branch"])
    user = re.search(r"forks/([^/]+)/", git(checkout, "remote", "get-url", fork).stdout)
    url = (
        f"{DIST_GIT}/fork/{user.group(1)}/rpms/{pkg.rpm_name}/diff/{state['target']}..{state['branch']}"
        if user
        else None
    )
    state.update(pushed=True, fork=fork, pr_url=url)
    f.write_text(json.dumps(state, indent=2) + "\n")
    util.info(
        f"   pushed {state['branch']} to {fork}; open the pull request: {url or '(see the fork on ' + DIST_GIT + ')'}"
    )
    return True


def cmd_dist_git(args) -> None:
    top = args.dir or (
        Path(os.environ[DIST_GIT_ENV]) if os.environ.get(DIST_GIT_ENV) else None
    )
    if not top and not args.push:
        util.die(f"say where the dist-git checkouts go: --dir DIR, or ${DIST_GIT_ENV}")
    pkgs = packages.select(args.root, args.crates, args.all)
    if args.all:
        pkgs = [
            p for p in pkgs if p.dist_git and p.dist_git.get("packaging") != "local"
        ]
    pkgs = (
        [p for s in build.build_stages(pkgs, args.root, warn_outside=False) for p in s]
        if pkgs
        else []
    )
    failed = []
    for pkg in pkgs:
        util.info(f"== {pkg.rpm_name} {pkg.version}")
        ok = (
            push_update(pkg)
            if args.push
            else prepare_update(
                pkg, top.expanduser().resolve(), args.branch, args.dry_run
            )
        )
        if not ok:
            failed.append(pkg.crate)
    if failed:
        util.die(f"dist-git failed for: {', '.join(failed)}")


def cmd_adopt(args) -> None:
    pkgs = packages.select(args.root, args.crates, args.all)
    if args.all:
        pkgs = [
            p
            for p in pkgs
            if p.dist_git is None
            and not p.compat
            and reviewplan.dist_git_has(p.rpm_name)
        ]
        util.info(
            f"in Fedora's dist-git: {', '.join(p.rpm_name for p in pkgs) or 'none'}"
        )
    failed = [
        p.crate for p in pkgs if not adopt(p, args.branch, args.dry_run, args.mark_only)
    ]
    if failed:
        util.die(f"adopt failed for: {', '.join(failed)}")
