"""rust-deps tmt: Fedora CI test metadata for a package."""

from __future__ import annotations

from dataclasses import dataclass, field
import json
import re
import shutil
import tomllib

from . import copr
from . import packages
from . import util

TMT_HEADER = (
    "# Generated by rust-deps from the spec and rust2rpm.toml; 'rust-deps regen' overwrites\n"
    "# changes.  Fedora CI runs this in dist-git pull requests; 'rust-deps tmt' runs it locally.\n"
)

TMT_FEATURES_SH = r"""#!/usr/bin/bash
# A crate that depends on $CRATE builds with each feature, offline, from the
# crates installed in /usr/share/cargo/registry (what dependent packages see).
set -euo pipefail
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
cd "$work"
mkdir src
: > src/lib.rs
bash -euo pipefail -c "$(rpm --eval '%cargo_prep')"
probe() {  # $1: what follows the version in the dependency's table
    cat > Cargo.toml <<EOF
[package]
name = "rust-deps-feature-probe"
version = "0.0.0"
edition = "2021"

[dependencies]
$CRATE = { version = "=$VERSION", $1 }
EOF
    rm -f Cargo.lock
    cargo check --offline --quiet
}
echo "== without features"
probe 'default-features = false'
for feature in $FEATURES; do
    echo "== feature $feature"
    if [ "$feature" = default ]; then
        # +default-devel stands for the default features, also of a crate that declares none
        probe 'default-features = true'
    else
        probe "default-features = false, features = [\"$feature\"]"
    fi
done
"""

TMT_UPSTREAM_SH = r"""#!/usr/bin/bash
# The crate's own tests, from the installed sources, run by the same
# %cargo_prep and %cargo_test commands as the spec's %check.
set -euo pipefail
commands=$(cd "$(dirname "$0")" && pwd)/check-commands
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
cp -a "/usr/share/cargo/registry/$CRATE-$VERSION/." "$work/"
cd "$work"
export RPM_BUILD_NCPUS=${RPM_BUILD_NCPUS:-$(nproc)}  # rpmbuild sets it; %cargo_test uses it
bash -euo pipefail -c "$(rpm --eval '%cargo_prep')"
while IFS= read -r command; do
    [ -n "$command" ] || continue
    echo "== $command"
    bash -euo pipefail -c "$(rpm --eval "$command")"
done < "$commands"
"""

TMT_EXECUTABLES_SH = r"""#!/usr/bin/bash
# Each executable of $PACKAGES starts and answers --help (or --version).
set -euo pipefail
found=0
for package in $PACKAGES; do
    for program in $(rpm -ql "$package" | grep '^/usr/bin/'); do
        found=1
        echo "== $program"
        "$program" --help > /dev/null || "$program" --version > /dev/null
    done
done
[ "$found" = 1 ] || { echo "no executables in $PACKAGES"; exit 1; }
"""


@dataclass
class TmtInfo:
    rpm_name: str
    crate: str
    version: str
    devel: list[str]  # the -devel subpackages
    features: list[str]  # feature subpackages (+feature-devel)
    binaries: list[str]  # packages with executables
    check_commands: list[str]  # the spec's %cargo_test lines, when %check runs
    test_requires: list[str]  # what the crate's tests need besides its own subpackages


def tmt_info(pkg: packages.LocalPackage) -> TmtInfo:
    """What the generated tests need to know, from the spec and the generated BuildRequires."""
    res = util.run(
        ["rpmspec", "-q", "--builtrpms", "--qf", "%{name}\n", str(pkg.spec)],
        capture_output=True,
    )
    if res.returncode:
        util.die(f"rpmspec failed on {pkg.spec}:\n{res.stderr}")
    names = list(dict.fromkeys(res.stdout.split()))
    devel = [n for n in names if n.endswith("-devel")]
    prefix = f"{pkg.rpm_name}+"
    features = [n[len(prefix) : -len("-devel")] for n in devel if n.startswith(prefix)]
    spec = pkg.spec.read_text()
    checks = []
    if copr.spec_runs_check(pkg.spec):
        section = re.search(
            r"^%check\n(.*?)(?=^%(?:endif|files|changelog|package)\b|\Z)",
            spec,
            re.M | re.S,
        )
        checks = (
            re.findall(r"^%cargo_test\b.*$", section.group(1), re.M) if section else []
        )
    requires = tomllib.loads(pkg.config_file.read_text()).get("requires", {})
    brs = [ln.strip() for ln in copr.build_info(pkg)[1] if ln.strip()] if checks else []
    extra = (
        list(requires.get("build", [])) + list(requires.get("test", []))
        if checks
        else []
    )
    return TmtInfo(
        pkg.rpm_name,
        pkg.crate,
        pkg.version,
        devel,
        features,
        [n for n in names if not n.endswith("-devel")],
        checks,
        list(dict.fromkeys(["cargo-rpm-macros"] + brs + extra)) if checks else [],
    )


def _yaml_list(items: list[str], indent: str) -> str:
    return "".join(f"{indent}- {json.dumps(i)}\n" for i in items)


def render_tmt(info: TmtInfo) -> dict[str, str]:
    """The tmt files for a package: path (relative to the package directory) -> content."""
    t = "tests/rust-deps"
    files = {
        ".fmf/version": "1\n",
        "plans/rust-deps.fmf": TMT_HEADER + f"summary: {info.rpm_name} as packaged\n"
        "discover:\n    how: fmf\n    filter: 'tag: rust-deps'\n"
        "prepare:\n"
        "  - name: documentation\n"
        "    summary: install %doc files too\n"
        "    # crates may include_str!() their README, which is %doc; container images install\n"
        "    # without documentation (tsflags=nodocs), which breaks their build\n"
        "    how: shell\n"
        "    order: 20\n"
        "    script: sed -i '/^tsflags=nodocs/d' /etc/dnf/dnf.conf\n"
        "execute:\n    how: tmt\n",
    }
    tests = TMT_HEADER + "tag: [rust-deps]\nframework: shell\nduration: 1h\n"
    env = f"    environment:\n        CRATE: {json.dumps(info.crate)}\n        VERSION: {json.dumps(info.version)}\n"
    if info.devel:
        tests += (
            "\n/subpackages:\n    summary: every -devel subpackage installs\n    require:\n"
            + _yaml_list(info.devel, "      ")
            + f"    test: rpm -q {' '.join(info.devel)}\n"
        )
        tests += (
            "\n/features:\n    summary: dependent crates build with each feature\n"
            "    description: a crate depending on it, offline, from the installed crates\n    require:\n"
            + _yaml_list(info.devel + ["cargo-rpm-macros"], "      ")
            + "    test: ./features.sh\n"
            + env
            + f"        FEATURES: {json.dumps(' '.join(f for f in info.features))}\n"
        )
        files[f"{t}/features.sh"] = TMT_FEATURES_SH
    if info.devel and info.check_commands:
        tests += (
            "\n/upstream-tests:\n    summary: the crate's own tests, as %check runs them\n"
            "    description: from the installed sources, with the spec's %cargo_test commands\n    require:\n"
            + _yaml_list(info.devel + info.test_requires, "      ")
            + "    test: ./upstream-tests.sh\n"
            + env
        )
        files[f"{t}/upstream-tests.sh"] = TMT_UPSTREAM_SH
        files[f"{t}/check-commands"] = "".join(c + "\n" for c in info.check_commands)
    if info.binaries:
        tests += (
            "\n/executables:\n    summary: the executables start\n    require:\n"
            + _yaml_list(info.binaries, "      ")
            + "    test: ./executables.sh\n"
            + f"    environment:\n        PACKAGES: {json.dumps(' '.join(info.binaries))}\n"
        )
        files[f"{t}/executables.sh"] = TMT_EXECUTABLES_SH
    files[f"{t}/main.fmf"] = tests
    return files


def write_tmt(pkg: packages.LocalPackage) -> None:
    """(Re)write the package's tmt files; files it wrote before and no longer needs go."""
    files = render_tmt(tmt_info(pkg))
    shutil.rmtree(pkg.dir / "tests" / "rust-deps", ignore_errors=True)
    for rel, content in files.items():
        f = pkg.dir / rel
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(content)
        if rel.endswith(".sh"):
            f.chmod(0o755)


def tmt_image(chroot: str) -> str:
    m = re.fullmatch(r"fedora-(\d+|rawhide)-[^-]+", chroot)
    if not m:
        util.die(
            f"'tmt' runs Fedora chroots only (a container of that release), not {chroot}"
        )
    return f"registry.fedoraproject.org/fedora:{m.group(1)}"


def cmd_tmt(args) -> None:
    if not shutil.which("tmt"):
        util.die("tmt is not installed (dnf install tmt+provision-container)")
    failed = []
    for pkg in packages.select(args.root, args.crates, args.all):
        if not (pkg.dir / "plans" / "rust-deps.fmf").exists():
            write_tmt(pkg)
        cmd = [
            "tmt",
            "--root",
            str(pkg.dir),
            "run",
            "--all",
            "provision",
            "--how",
            "container",
            "--image",
            tmt_image(args.chroot),
            "prepare",
            "--insert",
            "--how",
            "install",
            "--order",
            "30",
            "--copr",
            args.project,
        ]
        util.info(f"== tmt {pkg.crate}\n$ {' '.join(cmd)}")
        if not args.dry_run and util.run(cmd).returncode:
            failed.append(pkg.crate)
    if failed:
        util.die(f"tmt tests failed for: {', '.join(failed)}")
